version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: my_postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./db_data:/var/lib/postgresql/data
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        ports:
            - "5433:5432"
